server:
  port: 14514
spring:
  application:
    name: Mind-Lift-V3
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {{write u mysql url}}
    username: {{mysql username}}
    password: {{mysql password}}
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
mybatis:
  configuration:
    map-underscore-to-camel-case: false # 关闭下划线转驼峰
custom:
  token:
    token-expire-time: 1296000
  url:
    base-file-url: {{文件访问基础地址}} # 文件访问基础地址，记得根据Nginx修改这里
    star-api: https://agentapi.baidu.com/assistant/getAnswer
    bert-api: http://127.0.0.1:8000
  key:
    star-app-id: {{appid}}
    star-secret-key: {{key}}
    star-from: openapi
    star-access-token: {{token}}
    ALIBABA_CLOUD_ACCESS_KEY_ID: {{AccessKey}}
    ALIBABA_CLOUD_ACCESS_KEY_SECRET: {{Key}}


